name: Release Mac App

on:
  push:
    branches:
      - "release/mac/*"

jobs:
  trigger:
    runs-on: ["mac-mini", "mac", "macos"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine version
        id: version
        run: |
          chmod +x ./scripts/determine-version.sh
          ./scripts/determine-version.sh

      - uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.CUE_RELEASE_TOKEN }}
          repository: zhaolongzhong/cue-release
          event-type: mac-release
          client-payload: |
            {
              "ref": "${{ github.ref }}",
              "sha": "${{ github.sha }}",
              "branch": "${{ github.ref_name }}",
              "version_name": "${{ env.version_name }}",
              "version_code": "${{ env.version_code }}",
              "new_tag": "${{ env.new_tag }}"
            }
